#!/usr/bin/env python3
"""
MediaDigest - Cookie Helper for Docker Users
Exports cookies from a browser and saves them in the correct format for yt-dlp.

Usage:
    python3 tools/cookie_helper.py export --browser chrome --platform youtube
    python3 tools/cookie_helper.py check --platform youtube
    python3 tools/cookie_helper.py path --platform youtube

Requirements:
    - For browser export: pip install browser_cookie3
    - Alternatively, use a browser extension like "Get cookies.txt LOCALLY"
"""

import argparse
import os
import sys
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from core.config import COOKIES_DIR, BASE_DIR


def get_cookies_dir(platform=None):
    """Get cookies directory path."""
    if platform:
        return COOKIES_DIR / platform
    return COOKIES_DIR


def check_cookies(platform):
    """Check if cookie file exists for a platform."""
    cookie_path = COOKIES_DIR / platform / "cookies.txt"
    if cookie_path.exists():
        size = os.path.getsize(cookie_path)
        return {"exists": True, "path": str(cookie_path), "size": size}
    return {"exists": False, "path": str(cookie_path)}


def export_from_browser(browser, platform):
    """
    Export cookies from browser using browser_cookie3.
    Saves as Netscape cookies.txt format for yt-dlp.

    Note: browser_cookie3 is optional. Falls back to manual instructions.
    """
    try:
        import browser_cookie3
    except ImportError:
        print(f"browser_cookie3 not installed. Install: pip install browser_cookie3")
        print(f"\nAlternatively, export cookies manually:")
        print(f"  1. Install 'Get cookies.txt LOCALLY' browser extension")
        print(f"  2. Visit {platform}.com and log in")
        print(f"  3. Click the extension to export cookies")
        print(f"  4. Save to: {COOKIES_DIR / platform / 'cookies.txt'}")
        return False

    try:
        browser_map = {
            "chrome": browser_cookie3.chrome,
            "firefox": browser_cookie3.firefox,
            "edge": browser_cookie3.edge,
            "brave": browser_cookie3.brave,
            "opera": browser_cookie3.opera,
        }

        if browser not in browser_map:
            print(f"Unsupported browser: {browser}")
            print(f"Supported: {', '.join(browser_map.keys())}")
            return False

        cj = browser_map[browser](domain_name=platform + ".com")

        # Write Netscape cookies.txt format
        output_dir = COOKIES_DIR / platform
        output_dir.mkdir(parents=True, exist_ok=True)
        output_path = output_dir / "cookies.txt"

        with open(output_path, "w") as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# This file is generated by MediaDigest cookie_helper\n")
            f.write(
                "# You can also generate this file using a browser extension\n"
            )
            f.write(
                "# like 'Get cookies.txt LOCALLY' or 'EditThisCookie'\n\n"
            )

            for cookie in cj:
                secure = "TRUE" if cookie.secure else "FALSE"
                http_only = "TRUE" if hasattr(cookie, "has_nonstandard_attr") else ""
                domain = cookie.domain
                if domain.startswith("."):
                    domain = domain[1:]
                path = cookie.path or "/"
                expires = str(int(cookie.expires) if cookie.expires else 0)
                name = cookie.name
                value = cookie.value

                f.write(
                    f"{domain}\t{http_only}\t{path}\t{secure}\t"
                    f"{expires}\t{name}\t{value}\n"
                )

        print(f"Exported cookies to: {output_path}")
        return True

    except Exception as e:
        print(f"Error exporting cookies: {e}")
        print(f"\nFalling back to manual method:")
        print(f"  1. Install 'Get cookies.txt LOCALLY' browser extension")
        print(f"  2. Visit {platform}.com and log in")
        print(f"  3. Export and save to: {COOKIES_DIR / platform / 'cookies.txt'}")
        return False


def main():
    parser = argparse.ArgumentParser(description="MediaDigest Cookie Helper")
    sub = parser.add_subparsers(dest="command")

    # Check command
    check_parser = sub.add_parser("check", help="Check cookie status")
    check_parser.add_argument("--platform", "-p", required=True,
                              choices=["youtube", "bilibili", "twitter"])

    # Export command
    export_parser = sub.add_parser("export", help="Export cookies from browser")
    export_parser.add_argument("--browser", "-b", default="chrome",
                               choices=["chrome", "firefox", "edge", "brave", "opera"])
    export_parser.add_argument("--platform", "-p", required=True,
                               choices=["youtube", "bilibili", "twitter"])

    # Path command
    path_parser = sub.add_parser("path", help="Show cookie file path")
    path_parser.add_argument("--platform", "-p", required=True,
                             choices=["youtube", "bilibili", "twitter"])

    args = parser.parse_args()

    if args.command == "check":
        result = check_cookies(args.platform)
        if result["exists"]:
            print(f"Cookie file found: {result['path']}")
            print(f"Size: {result['size']} bytes")
        else:
            print(f"No cookie file for {args.platform}")
            print(f"Expected at: {result['path']}")

    elif args.command == "export":
        export_from_browser(args.browser, args.platform)

    elif args.command == "path":
        path = COOKIES_DIR / args.platform / "cookies.txt"
        print(str(path))

    else:
        parser.print_help()


if __name__ == "__main__":
    main()
